server:
  port: 8080
  servlet:
    context-path: /wyyl

spring:
  #Springmvc的视图解析器
  mvc:
    view:
      prefix: WEB-INF/
      suffix: .jsp
    # 设置匹配.action后缀的请求的配置
    pathmatch:
      use-registered-suffix-pattern: true
      use-suffix-pattern: false
      #映射文件所扫描的包路径，首先要增加Mybatis的pom的支持
  datasource:
    username: tom
    password: 123456
    url: jdbc:mysql://172.3.18.23:3306/wyyl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://172.3.18.23:27017/wyyl
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


mybatis:
  type-aliases-package: com.wm.
  mapper-locations: classpath:mappers/*.xml




